Repository SUSE/DeepSea, pull requests merged in 2018-07, with the labels that each got.

#1208 Remove _minion_check since it is superceded my minions.ready
  srv/modules/runners/validate.py
Labels: cleanup

#1223 Use safe_dump rather than dump
  srv/modules/runners/proposal.py
Labels: bug

#1219 build/ops: add jq runtime dependency to spec file
  deepsea.spec.in
Labels: bug, needs backport

#1236 passed arg was not changed in sls file after changed in function header
  srv/salt/ceph/remove/storage/drain/default.sls
Labels: bug

#1235 apparmor: install apparmor-utils package on SUSE
  srv/salt/ceph/apparmor/install/SUSE.sls
Labels: needs backport

#896 Adding more information to the man pages
  man/deepsea-commands.7
  man/deepsea-customization.7
  man/deepsea-mines.7
  man/deepsea-stage-0.7
  man/deepsea-stage-1.7
  man/deepsea-stage-2.7
  man/deepsea-stage-3.7
  man/deepsea-stage-4.7
  man/deepsea-stage-5.7
Labels: documentation, needs backport

#1233 qa: refactor health-ok.sh, drop health-{mds,rgw}.sh
  Makefile
  deepsea.spec.in
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/helper.sh
  qa/common/policy.sh
  qa/suites/basic/health-mds.sh
  qa/suites/basic/health-nfs-ganesha.sh
  qa/suites/basic/health-ok.sh
  qa/suites/basic/health-rgw.sh
  srv/salt/ceph/functests/1node/apparmor/init.sls
  srv/salt/ceph/functests/1node/init.sls
  srv/salt/ceph/functests/1node/keyrings/init.sls
  srv/salt/ceph/functests/1node/macros/os_switch/init.sls
  srv/salt/ceph/functests/1node/openstack/default.sls
  srv/salt/ceph/functests/1node/openstack/init.sls
  srv/salt/ceph/functests/1node/openstack/prefix.sls
  srv/salt/ceph/functests/1node/quiescent/init.sls
  srv/salt/ceph/functests/1node/restart/common.sls
  srv/salt/ceph/functests/1node/restart/mds.sls
  srv/salt/ceph/functests/1node/restart/mgr.sls
  srv/salt/ceph/functests/1node/restart/mon.sls
  srv/salt/ceph/functests/1node/restart/rgw.sls
  srv/salt/ceph/functests/1node/tuned/init.sls
  srv/salt/ceph/functests/1node/tuned/off/init.sls
Labels: DNM, QA

#1244 qa: add all possible dummy osd-configurations
  Makefile
  qa/osd-config/ovh/README.md
  qa/osd-config/ovh/bs_dedicated_db.yaml
  qa/osd-config/ovh/bs_dedicated_db_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal.yaml
  qa/osd-config/ovh/bs_dedicated_wal_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/fs_dedicated_journal.yaml
  qa/osd-config/ovh/fs_dedicated_journal_crypt.yaml
Labels: QA, enhancement, needs backport

#1246 cli: filter out test.nop steps and don't report [init] step errors
  cli/monitors/terminal_outputter.py
  cli/stage_parser.py
  cli/tests/test_stage_parse.py
Labels: CLI, bug

#1245 qa/common: create btrfs subvolumes after Stage 0
  qa/common/common.sh
  qa/common/helper.sh
  qa/suites/basic/health-ok.sh
Labels: QA, needs backport

#1251 rescind: prevent empty rendering of ceph.rescind.tuned state file
  srv/salt/ceph/rescind/tuned/default.sls
Labels: needs backport

#1249 build/ops: streamline qa %files section
  deepsea.spec.in
Labels: build/ops
