Repository SUSE/DeepSea, pull requests merged in 2018-06, with the labels that each got.

#1160 Install product specific package when on SLES
  Makefile
  deepsea.spec.in
  srv/salt/ceph/macros/README.md
  srv/salt/ceph/metapackage/SUSE-15.sls
  srv/salt/ceph/metapackage/default.sls
  srv/salt/ceph/metapackage/init.sls
  srv/salt/ceph/packages/common/default.sls
  srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
  srv/salt/ceph/stage/prep/master/default.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-update-no-reboot.sls
  srv/salt/ceph/stage/prep/minion/default.sls
Labels: needs backport

#1149 cli: fix stage parsing for salt 2018
  Makefile
  cli/.coveragerc
  cli/.pylintrc
  cli/common.py
  cli/deepsea.py
  cli/monitor.py
  cli/monitors/terminal_outputter.py
  cli/run-unit-tests.sh
  cli/salt_event.py
  cli/stage_executor.py
  cli/stage_parser.py
  cli/tests/Dockerfile
  cli/tests/__init__.py
  cli/tests/helper.py
  cli/tests/start.sh
  cli/tests/test_monitor.py
  cli/tests/test_stage_parse.py
  srv/salt/_modules/deepsea.py
  srv/salt/ceph/monitoring/prometheus/update_service_discovery.sls
Labels: CLI, enhancement, needs backport

#1164 [Backport][SES5] inital apparmor support
  Makefile
  deepsea.spec.in
  srv/modules/runners/ready.py
  srv/salt/ceph/apparmor/default-complain.sls
  srv/salt/ceph/apparmor/default-disable.sls
  srv/salt/ceph/apparmor/default-enforce.sls
  srv/salt/ceph/apparmor/default.sls
  srv/salt/ceph/apparmor/files/ceph.d/common
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mds
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mgr
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mon
  srv/salt/ceph/apparmor/files/usr.bin.ceph-osd
  srv/salt/ceph/apparmor/files/usr.bin.radosgw
  srv/salt/ceph/apparmor/files/usr.sbin.httpd-prefork
  srv/salt/ceph/apparmor/files/usr.sbin.oaconfig
  srv/salt/ceph/apparmor/init.sls
  srv/salt/ceph/apparmor/install/SUSE.sls
  srv/salt/ceph/apparmor/install/default.sls
  srv/salt/ceph/apparmor/install/init.sls
  srv/salt/ceph/apparmor/profiles.sls
  srv/salt/ceph/macros/README.md
  srv/salt/ceph/macros/os_switch.sls
  srv/salt/ceph/smoketests/apparmor/init.sls
Labels: feature, needs-qa

#1166 Fix bare excepts in fs module and log a complete traceback
  srv/salt/_modules/fs.py
Labels: cleanup

#1159 Add codecov integration to Travis CI
  .codecov.yml
  tox.ini
Labels: question

#1180 cli: common: fix terminal utf-8 support detector
  cli/common.py
Labels: CLI, bug, needs backport

#1163 fix lint issues
  Makefile
  srv/modules/runners/cephprocesses.py
  srv/modules/runners/cmd.py
  srv/salt/_modules/cephprocesses.py
  srv/salt/_modules/wait.py
Labels: cleanup

#1079 apparmor: add initial profiles
  Makefile
  deepsea.spec.in
  srv/modules/utils/ready.py
  srv/salt/ceph/apparmor/default-complain.sls
  srv/salt/ceph/apparmor/default-disable.sls
  srv/salt/ceph/apparmor/default-enforce.sls
  srv/salt/ceph/apparmor/default.sls
  srv/salt/ceph/apparmor/files/ceph.d/common
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mds
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mgr
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mon
  srv/salt/ceph/apparmor/files/usr.bin.ceph-osd
  srv/salt/ceph/apparmor/files/usr.bin.radosgw
  srv/salt/ceph/apparmor/files/usr.sbin.httpd-prefork
  srv/salt/ceph/apparmor/files/usr.sbin.oaconfig
  srv/salt/ceph/apparmor/init.sls
  srv/salt/ceph/apparmor/install/SUSE.sls
  srv/salt/ceph/apparmor/install/default.sls
  srv/salt/ceph/apparmor/install/init.sls
  srv/salt/ceph/apparmor/profiles.sls
  srv/salt/ceph/smoketests/apparmor/init.sls
  srv/salt/ceph/smoketests/init.sls
Labels: feature
