Repository SUSE/DeepSea, pull requests merged in 2018-04, with the labels that each got.

#1023 Support kwargs in orchestrations
  srv/modules/runners/proposal.py
  srv/salt/ceph/stage/discovery/default-nvme.sls
Labels: needs backport

#1061 Prefer underscore device names
  srv/salt/_modules/osd.py
  srv/salt/_modules/proposal.py
  tests/unit/_modules/test_osd.py
Labels: needs backport

#1049 Return a single device
  srv/salt/_modules/cephinspector.py
Labels: needs backport

#1051 Add salt2018 support
  .gitignore
  srv/modules/runners/filequeue.py
  srv/modules/runners/fs.py
  srv/modules/runners/net.py
  srv/modules/runners/populate.py
  srv/modules/runners/proposal.py
  srv/modules/runners/validate.py
  srv/salt/_modules/cephdisks.py
  srv/salt/_modules/cephimages.py
  srv/salt/_modules/cephinspector.py
  srv/salt/_modules/cephprocesses.py
  srv/salt/_modules/fs.py
  srv/salt/_modules/helper.py
  srv/salt/_modules/kernel.py
  srv/salt/_modules/keyring.py
  srv/salt/_modules/multi.py
  srv/salt/_modules/openattic.py
  srv/salt/_modules/osd.py
  srv/salt/_modules/packagemanager.py
  srv/salt/_modules/proposal.py
  srv/salt/_modules/retry.py
  srv/salt/_modules/rgw.py
  srv/salt/_modules/zypper_locks.py
  srv/salt/ceph/reactor/initialize.sls
  srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
  srv/salt/ceph/stage/prep/master/default.sls
  tests/unit/_modules/test_cephdisks.py
  tests/unit/_modules/test_kernel.py
  tests/unit/_modules/test_osd.py
  tests/unit/_modules/test_packagemanager.py
  tests/unit/_modules/test_rgw.py
  tests/unit/_modules/test_validate.py
  tests/unit/helper/fixtures.py
  tox.ini
Labels: bug, enhancement, needs-qa

#1067 Add push,add back to filequeue
  srv/modules/runners/filequeue.py
Labels: cleanup

#1084 runners/populate: don't create public_address proposals for mon/igw
  srv/modules/runners/populate.py
Labels: cleanup

#1099 Add missing role to cephprocesses map
  srv/salt/_modules/cephprocesses.py
Labels: bug, needs backport

#1054 Support restart smoketests
  Makefile
  deepsea.spec.in
  srv/salt/ceph/smoketests/restart/common.sls
  srv/salt/ceph/smoketests/restart/mds.sls
  srv/salt/ceph/smoketests/restart/mgr.sls
  srv/salt/ceph/smoketests/restart/mon.sls
  srv/salt/ceph/smoketests/restart/rgw.sls
  srv/salt/ceph/tests/restart/changed_pid.sls
  srv/salt/ceph/tests/restart/mds/change/init.sls
  srv/salt/ceph/tests/restart/mds/changed_pid.sls
  srv/salt/ceph/tests/restart/mds/forced/init.sls
  srv/salt/ceph/tests/restart/mds/nochange/init.sls
  srv/salt/ceph/tests/restart/mds/reset.sls
  srv/salt/ceph/tests/restart/mds/same_pid.sls
  srv/salt/ceph/tests/restart/mds/save_pid.sls
  srv/salt/ceph/tests/restart/mds/setup.sls
  srv/salt/ceph/tests/restart/mds/teardown.sls
  srv/salt/ceph/tests/restart/mgr/change/init.sls
  srv/salt/ceph/tests/restart/mgr/changed_pid.sls
  srv/salt/ceph/tests/restart/mgr/forced/init.sls
  srv/salt/ceph/tests/restart/mgr/nochange/init.sls
  srv/salt/ceph/tests/restart/mgr/reset.sls
  srv/salt/ceph/tests/restart/mgr/same_pid.sls
  srv/salt/ceph/tests/restart/mgr/save_pid.sls
  srv/salt/ceph/tests/restart/mgr/setup.sls
  srv/salt/ceph/tests/restart/mgr/teardown.sls
  srv/salt/ceph/tests/restart/mon/change/init.sls
  srv/salt/ceph/tests/restart/mon/changed_pid.sls
  srv/salt/ceph/tests/restart/mon/forced/init.sls
  srv/salt/ceph/tests/restart/mon/nochange/init.sls
  srv/salt/ceph/tests/restart/mon/reset.sls
  srv/salt/ceph/tests/restart/mon/same_pid.sls
  srv/salt/ceph/tests/restart/mon/save_pid.sls
  srv/salt/ceph/tests/restart/mon/setup.sls
  srv/salt/ceph/tests/restart/mon/teardown.sls
  srv/salt/ceph/tests/restart/reset.sls
  srv/salt/ceph/tests/restart/rgw/change/init.sls
  srv/salt/ceph/tests/restart/rgw/changed_pid.sls
  srv/salt/ceph/tests/restart/rgw/forced/init.sls
  srv/salt/ceph/tests/restart/rgw/nochange/init.sls
  srv/salt/ceph/tests/restart/rgw/reset.sls
  srv/salt/ceph/tests/restart/rgw/same_pid.sls
  srv/salt/ceph/tests/restart/rgw/save_pid.sls
  srv/salt/ceph/tests/restart/rgw/setup.sls
  srv/salt/ceph/tests/restart/rgw/teardown.sls
  srv/salt/ceph/tests/restart/same_pid.sls
  srv/salt/ceph/tests/restart/save_pid.sls
  srv/salt/ceph/tests/restart/setup.sls
  srv/salt/ceph/tests/restart/teardown.sls
Labels: QA

#1115 Refactor basic integration test scripts for Mimic/SES6
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/helper.sh
  qa/common/json.sh
  qa/common/nfs-ganesha.sh
  qa/common/policy.sh
  qa/common/pool.sh
  qa/common/rgw.sh
  qa/suites/basic/health-igw.sh
  qa/suites/basic/health-mds.sh
  qa/suites/basic/health-nfs-ganesha.sh
  qa/suites/basic/health-ok.sh
  qa/suites/basic/health-openattic.sh
  qa/suites/basic/health-rgw.sh
  qa/suites/ceph-test/librbd.sh
  qa/suites/ceph-test/pynfs.sh
Labels: QA

#1116 Implement __utils__ and fix cached-runners issue
  Makefile
  deepsea.spec.in
  etc/salt/master.d/modules.conf
  srv/modules/runners/deepsea_minions.py
  srv/modules/runners/fs.py
  srv/modules/runners/net.py
  srv/modules/runners/populate.py
  srv/modules/runners/proposal.py
  srv/modules/runners/ready.py
  srv/modules/runners/validate.py
  srv/modules/utils/__init__.py
  srv/modules/utils/deepsea_minions.py
  srv/modules/utils/ready.py
  tests/unit/runners/test_ready.py
  tests/unit/runners/test_validate.py
Labels: bug
