Repository SUSE/DeepSea, pull requests merged in 2018-08, with the labels that each got.

#1256 Fix indentation for unit tests
  tests/unit/_modules/test_osd.py
  tests/unit/_modules/test_rgw.py
  tests/unit/helper/output.py
  tests/unit/runners/test_changed.py
  tests/unit/runners/test_push.py
  tests/unit/runners/test_status.py
  tests/unit/runners/test_ui_iscsi.py
  tests/unit/runners/test_ui_rgw.py
  tests/unit/runners/test_validate.py
Labels: cleanup

#1250 qa: health-ok.sh: enable testing of OSD configurations
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/helper.sh
  qa/common/policy.sh
  qa/common/zypper.sh
  qa/suites/basic/health-ok.sh
Labels: QA, needs backport

#1253 qa: add script to test Stage 5
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/helper.sh
  qa/common/json.sh
  qa/common/policy.sh
  qa/common/zypper.sh
  qa/suites/basic/health-ok.sh
  qa/suites/basic/stage-5.sh
Labels: QA, needs backport

#1262 Add checklist to Pullrequest template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cleanup, enhancement

#1275 qa/deploy: handle possibility that deepsea-cli is not installed
  qa/common/deploy.sh
Labels: QA

#1277 qa: run lsblk and ceph-disk on storage node only
  qa/common/common.sh
Labels: QA

#1273 Fix wait.py duplications and wrong class invocation.
  srv/salt/_modules/wait.py
Labels: bug

#1283 qa: common/helper: storage-only node might be master node
  qa/common/helper.sh
Labels: QA

#1222 Refactor device detection, allow override
  srv/salt/_modules/cephdisks.py
  srv/salt/_modules/osd.py
  srv/salt/_modules/proposal.py
  tests/unit/_modules/test_cephdisks.py
  tests/unit/_modules/test_osd.py
  tests/unit/_modules/test_proposal.py
Labels: needs backport

#1292 populate: don't create role-mon yml line during engulf (bsc#1104781)
  srv/modules/runners/populate.py
Labels: bug, needs backport

#1296 qa: common/deploy: run "zypper ps -s" on all nodes
  qa/common/deploy.sh
  qa/common/rgw.sh
Labels: QA, backported

#1298 Add unittests for wait.just
  srv/salt/_modules/wait.py
  tests/unit/_modules/test_wait.py
Labels: needs backport

#1255 Change the default for stage to update no reboot
  man/deepsea-customization.7
  man/deepsea-stage-0.7
  qa/common/common.sh
  srv/salt/ceph/stage/prep/master/default-update-reboot.sls
  srv/salt/ceph/stage/prep/master/default.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default.sls
Labels: needs backport

#1303 qa: use "systemctl --no-pager --full status" and restart rsyslog service after installing curl RPM
  qa/common/common.sh
  qa/common/rgw.sh
Labels: QA, backported

#1305 stage/prep: reinstate single quotes around deepsea_minions tgt, plus some qa fixes
  qa/common/pool.sh
  qa/suites/basic/health-nfs-ganesha.sh
  qa/suites/basic/health-ok.sh
  srv/salt/ceph/stage/prep/master/default.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default.sls
Labels: backported

#1299 cephinspector: use cephdisks.device in engulf (bsc#1082994)
  srv/salt/_modules/cephinspector.py
Labels: bug, needs backport

#1314 Move from tgt_type to expr_form in .py files
  srv/modules/runners/advise.py
  srv/modules/runners/cephprocesses.py
  srv/modules/runners/remove.py
Labels: bug

#1313 Refactor dashboards
  Makefile
  srv/salt/ceph/functests/1node/grafana/init.sls
  srv/salt/ceph/functests/1node/init.sls
  srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
  srv/salt/ceph/monitoring/grafana/files/ceph-osd.json
  srv/salt/ceph/monitoring/grafana/files/ceph-pools.json
  srv/salt/ceph/monitoring/grafana/files/ceph-rbd.json
  srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json
  srv/salt/ceph/monitoring/grafana/files/ceph-rgw.json
  srv/salt/ceph/monitoring/grafana/files/node.json
  srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
  srv/salt/ceph/tests/grafana/running.sls
Labels: enhancement

#1302 OSD Migration for changed disk slots
  srv/modules/runners/proposal.py
  srv/modules/runners/replace.py
  srv/salt/_modules/cephdisks.py
  srv/salt/_modules/osd.py
  srv/salt/_modules/proposal.py
  tests/unit/_modules/test_cephdisks.py
  tests/unit/runners/test_proposal.py
Labels: needs backport, priority

#1325 [SES5] Add make tarball to usage
  Makefile
Labels: documentation

#1323 [SES5] Add basic alerting
  srv/salt/ceph/monitoring/prometheus/alertmanager.sls
  srv/salt/ceph/monitoring/prometheus/files/alertmanager.yml.j2
  srv/salt/ceph/monitoring/prometheus/files/alerts.yml.j2
  srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
  srv/salt/ceph/monitoring/prometheus/init.sls
Labels: feature

#1317 [SES5] qa: reinstate health-openattic.sh
  health-igw.sh
  health-openattic.sh
  qa/suites/basic/health-openattic.sh
Labels: QA

#1316 Add more functests to init.sls <functests.1node>
  srv/salt/ceph/functests/1node/init.sls
Labels: QA

#1326 NFS-Ganesha + Cephfs: Add cache config options
  srv/salt/ceph/ganesha/files/ganesha.conf.j2
Labels: backported, bug
