Repository SUSE/DeepSea, pull requests merged in 2018-05, with the labels that each got.

#1120 [DNM] [RFC] use jinja macros for simpler dist switch in init.sls
  Makefile
  deepsea.spec.in
  srv/salt/ceph/macros/os_switch.sls
  srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/init.sls
Labels: DNM, enhancement

#1127 macros/os_switch: consider not only dirs but also files, add README
  srv/salt/ceph/macros/README.md
  srv/salt/ceph/macros/os_switch.sls
Labels: enhancement

#1125 qa: ensure ceph-test RPM is installed
  qa/common/rbd.sh
Labels: QA, needs backport

#1134 be able to run condensed smoketests
  srv/salt/ceph/smoketests/init.sls
  srv/salt/ceph/smoketests/restart/common.sls
Labels: enhancement

#1133 Add ceph/test/restart/$role sub-directories to make/spec files
  Makefile
  deepsea.spec.in
  srv/salt/ceph/smoketests/restart/common.sls
Labels: bug

#1147 macros: fix os_switch macro to work on minions.
  Makefile
  deepsea.spec.in
  srv/salt/ceph/macros/os_switch.sls
  srv/salt/ceph/smoketests/init.sls
  srv/salt/ceph/smoketests/macros/os_switch/init.sls
  srv/salt/ceph/tests/os_switch/custom.sls
  srv/salt/ceph/tests/os_switch/file.sls
  srv/salt/ceph/tests/os_switch/init.sls
Labels: bug

#1152 Add py-coverage
  .coveragerc
  tox.ini
Labels: enhancement

#1155 Fix salt-api validation
  srv/modules/runners/validate.py
Labels: bug, needs backport

#1085 [backport][SES5] runners/populate: don't create public_address proposals for mon/igw
  srv/modules/runners/populate.py
Labels: cleanup

#1156 [Backport] [SES5] Fix salt-api validation
  srv/modules/runners/validate.py
Labels: bug
