Repository SUSE/DeepSea, pull requests merged in 2018-03, with the labels that each got.

#892 Add restart mechanism to stage.4 related services
  Makefile
  deepsea.spec.in
  srv/salt/_modules/cephprocesses.py
  srv/salt/ceph/igw/default.sls
  srv/salt/ceph/igw/restart/default.sls
  srv/salt/ceph/igw/restart/force/default.sls
  srv/salt/ceph/igw/restart/force/init.sls
  srv/salt/ceph/igw/restart/init.sls
  srv/salt/ceph/igw/restart/reload/default.sls
  srv/salt/ceph/igw/restart/reload/init.sls
  srv/salt/ceph/rgw/restart/controlled/default.sls
  srv/salt/ceph/stage/cephfs/core/default.sls
  srv/salt/ceph/stage/cephfs/core/init.sls
  srv/salt/ceph/stage/cephfs/default.sls
  srv/salt/ceph/stage/ganesha/core/default.sls
  srv/salt/ceph/stage/ganesha/core/init.sls
  srv/salt/ceph/stage/ganesha/default.sls
  srv/salt/ceph/stage/iscsi/core/default.sls
  srv/salt/ceph/stage/iscsi/core/init.sls
  srv/salt/ceph/stage/iscsi/default.sls
  srv/salt/ceph/stage/openattic/core/default.sls
  srv/salt/ceph/stage/openattic/core/init.sls
  srv/salt/ceph/stage/openattic/default.sls
  srv/salt/ceph/stage/radosgw/core/default.sls
  srv/salt/ceph/stage/radosgw/core/init.sls
  srv/salt/ceph/stage/radosgw/default.sls
Labels: enhancement, needs backport, needs-qa

#964 correct workflow for deepsea_minion setting
  srv/modules/runners/validate.py
Labels: documentation, enhancement

#941 [backport][SES5] Avoid random _client_node name
  qa/common/helper.sh
Labels: QA

#987 monitoring: move node_exporter install to its own sls
  srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
  srv/salt/ceph/monitoring/prometheus/exporters/node_exporter_package.sls
  srv/salt/ceph/stage/configure/default.sls
Labels: bug

#974 Check for WAL/DB present but not configured
  srv/salt/_modules/osd.py
  tests/unit/_modules/test_osd.py
Labels: needs backport

#951 populate: support multiple public, cluster networks in engulf (bsc#1076010)
  srv/modules/runners/populate.py
Labels: bug, needs backport

#1007 Add a --mini switch to the health-ok suite
  qa/suites/basic/health-ok.sh
Labels: QA, enhancement, needs backport

#1006 Copy the generated setup.py back to the builddir in order to make tox happy
  Makefile
Labels: bug

#980 qa: run zypper refresh in try/wait loop
  deepsea.spec.in
  qa/common/common.sh
  qa/common/nfs-ganesha.sh
  qa/common/rgw.sh
Labels: QA, needs backport, needs-qa

#1015 [SES5] qa: run zypper refresh in try/wait loop
  deepsea.spec.in
  qa/common/common.sh
  qa/common/nfs-ganesha.sh
  qa/common/rgw.sh
Labels: QA

#1014 qa: common: dump systemd log when a stage fails
  qa/common/helper.sh
Labels: QA

#983 QA test - migration from filestore to bluestore
  qa/common/common.sh
  qa/suites/ceph-test/fs_to_bs_migration.sh
Labels: QA

#1024 select runner: add format option to get a formatted list of minions
  srv/modules/runners/select.py
Labels: enhancement

#1013 monitoring: remove conditional for node_exporter config
  srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
  srv/salt/ceph/monitoring/prometheus/exporters/node_exporter_package.sls
  srv/salt/ceph/stage/configure/default.sls
Labels: bug

#1030 apparmor: add initial profiles
  Makefile
  deepsea.spec.in
  srv/modules/runners/ready.py
  srv/salt/ceph/apparmor/complain.sls
  srv/salt/ceph/apparmor/disable.sls
  srv/salt/ceph/apparmor/files/ceph.d/common
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mds
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mgr
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mon
  srv/salt/ceph/apparmor/files/usr.bin.ceph-osd
  srv/salt/ceph/apparmor/files/usr.bin.radosgw
  srv/salt/ceph/apparmor/init.sls
Labels: feature, needs-qa

#1012 [backport][SES5]populate: support multiple public, cluster networks in engulf (bsc#1076010)
  srv/modules/runners/populate.py
Labels: bug

#1033 Fix bool kv subscription issue (regression from #982)
  srv/modules/runners/validate.py
Labels: bug

#1034 Correct init variable
  srv/salt/ceph/redeploy/nodes/init.sls
Labels: needs backport

#1036 Remove OSDState
  man/deepsea-commands.7
  srv/salt/_modules/osd.py
Labels: cleanup

#1043 [backport][SES5] qa: rados_write_test
  qa/common/common.sh
  qa/suites/basic/health-ok.sh
  qa/suites/basic/health-rgw.sh
Labels: needs-qa
