Repository SUSE/DeepSea, pull requests merged in 2018-09, with the labels that each got.

#1338 monitoring: fix rbd_exporter pool parsing for ids > 9
  srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh
Labels: backported, bug

#1339 [backport][ses5] monitoring: fix rbd_exporter pool parsing for ids > 9
  srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh
Labels: bug

#1347 Fix an actually funny (maybe intended) typo.
  srv/modules/runners/proposal.py
Labels: needs backport

#1346 qa: don't initially delete openstack pools
  qa/common/common.sh
  qa/common/helper.sh
  qa/common/pool.sh
  qa/suites/basic/health-ok.sh
  srv/salt/ceph/functests/1node/init.sls
  srv/salt/ceph/functests/1node/openstack/default.sls
  srv/salt/ceph/functests/1node/openstack/prefix.sls
Labels: needs backport

#1342 tuned: make stanza names unique
  srv/salt/ceph/tuned/mgr/default.sls
  srv/salt/ceph/tuned/mon/default.sls
  srv/salt/ceph/tuned/osd/default.sls
Labels: needs backport

#1353 cli: support list of sls ids in salt.state orch function
  cli/deepsea.py
  cli/monitor.py
  cli/stage_parser.py
  cli/tests/test_stage_parse.py
Labels: CLI, bug, feature

#1355 qa: reinstate rbd client test as part of tier2
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/pool.sh
  qa/suites/basic/health-ok.sh
Labels: QA, needs backport

#1344 monitoring: fix fs fillup time query
  srv/salt/ceph/monitoring/grafana/files/node.json
Labels: bug

#1345 [backport][SES5] monitoring: fix fs fillup time query
  srv/salt/ceph/monitoring/grafana/files/node.json
Labels: bug

#1356 [forwardport][master] cli: support list of sls ids in salt.state orch function
  cli/deepsea.py
  cli/monitor.py
  cli/stage_parser.py
  cli/tests/test_stage_parse.py
Labels: bug

#1361 man: add line break between separate commands.
  man/deepsea-minions.7
Labels: needs backport

#1354 [backport][SES5] qa: add openstack functional test to CI
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/helper.sh
  qa/common/pool.sh
  qa/suites/basic/health-ok.sh
  srv/salt/ceph/functests/1node/init.sls
  srv/salt/ceph/functests/1node/openstack/default.sls
  srv/salt/ceph/functests/1node/openstack/prefix.sls
  srv/salt/ceph/tuned/mgr/default.sls
  srv/salt/ceph/tuned/mon/default.sls
  srv/salt/ceph/tuned/osd/default.sls
Labels: QA

#1359 remove/replace interference fixes
  srv/modules/runners/remove.py
  srv/modules/runners/replace.py
Labels: bug, needs backport

#1360 [backport][SES5] remove/replace interference fixes
  srv/modules/runners/remove.py
  srv/modules/runners/replace.py
Labels: bug

#1366 [SES5] cli: fix parsing of salt.runner when used inside state files
  cli/stage_parser.py
  cli/tests/test_stage_parse.py
Labels: CLI, bug

#1362 fixed problem in stage.0 with error message no minion found in metap…
  srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default.sls
Labels: needs backport

#1369 [backport][SES5] stage 0: update salt mines correctly without restarting minion
  srv/salt/ceph/mines/default.sls
Labels: CLI

#1377 qa/deploy: use jq instead of python in salt_api_test
  qa/common/common.sh
  qa/common/deploy.sh
Labels: QA

#1374 [backport][SES5] qa/deploy: use jq instead of python in salt_api_test
  qa/common/common.sh
  qa/common/deploy.sh
Labels: QA

#1383 qa/health-ok: repeat Stage 0 only once
  qa/common/helper.sh
  qa/suites/basic/health-ok.sh
Labels: QA

#1384 [backport][SES5] qa/health-ok: repeat Stage 0 only once and dump lrbd.service status in certain failure cases
  qa/common/helper.sh
  qa/suites/basic/health-ok.sh
Labels: QA

#1392 [SES5] Remove error condition, empty cluster network is valid
  srv/modules/runners/populate.py
Labels: bug

#1388 qa/deploy: fix error-reporting issues
  qa/common/deploy.sh
Labels: QA, needs backport

#1391 Remove error condition, empty cluster network is valid
  srv/modules/runners/populate.py
Labels: bug, needs backport

#1393 [backport] [SES5] qa/deploy: fix error-reporting issues
  qa/common/deploy.sh
Labels: QA

#1386 cli: refer to orchestration instead of stage
  cli/monitors/terminal_outputter.py
Labels: CLI

#1394 qa: drop health-ok.sh and associated scripting
  Makefile
  deepsea.spec.in
  qa/README
  qa/README.wip
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/helper.sh
  qa/common/json.sh
  qa/common/nfs-ganesha.sh
  qa/common/policy.sh
  qa/common/pool.sh
  qa/common/rbd.sh
  qa/common/rgw.sh
  qa/common/zypper.sh
  qa/osd-config/ovh/README.md
  qa/osd-config/ovh/bs_dedicated_db.yaml
  qa/osd-config/ovh/bs_dedicated_db_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal.yaml
  qa/osd-config/ovh/bs_dedicated_wal_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/fs_dedicated_journal.yaml
  qa/osd-config/ovh/fs_dedicated_journal_crypt.yaml
  qa/suites/basic/health-ok.sh
  qa/suites/basic/stage-5.sh
  qa/suites/ceph-test/fs_to_bs_migration.sh
  qa/suites/ceph-test/librbd.sh
  qa/suites/ceph-test/pynfs.sh
Labels: QA
