Repository SUSE/DeepSea, pull requests merged in 2018-10, with the labels that each got.

#1406 [SES5] qa: always report completion of deploy phase
  qa/common/deploy.sh
Labels: QA

#1387 Fix Engulf on Master
  Makefile
  deepsea.spec.in
  srv/modules/runners/populate.py
  srv/salt/_modules/cephinspector.py
  srv/salt/_modules/functest.py
  srv/salt/ceph/functests/1node/engulf/init.sls
  srv/salt/ceph/functests/1node/init.sls
  srv/salt/ceph/tests/engulf/pillar-save.sls
  srv/salt/ceph/tests/engulf/pillar-verify.sls
  srv/salt/ceph/tests/engulf/profile-verify.sls
  srv/salt/ceph/tests/engulf/proposal-backup.sls
  srv/salt/ceph/tests/engulf/proposal-restore.sls
Labels: bug

#1417 Use FQDN hostname also for MASTER_MINION
  qa/common/deploy.sh
Labels: needs-forwardport

#1400 Remove journal_size if present
  srv/modules/runners/push.py
Labels: needs-backport

#1426 [SES5] qa/iscsi: refactor iscsi_mount_and_sanity_test and enable targetcli debug logging
  qa/common/common.sh
  qa/common/deploy.sh
Labels: QA

#1422 fix _insert_replace_flag func header bsc#1110939
  srv/modules/runners/replace.py
  srv/salt/_modules/osd.py
  tests/unit/_modules/test_osd.py
Labels: bug, needs-forwardport

#1431 Add validation for pending updates
  srv/modules/runners/populate.py
  srv/modules/runners/validate.py
  srv/modules/utils/settings.py
  srv/salt/_modules/packagemanager.py
  srv/salt/ceph/mines/default.sls
  tests/unit/_modules/test_packagemanager.py
  tests/unit/runners/test_validate.py
Labels: enhancement

#1429 Refactor cephprocesses module and add tests for it V2
  Makefile
  deepsea.spec.in
  man/deepsea-stage-0.7
  srv/modules/runners/cephprocesses.py
  srv/pillar/ceph/blacklist.sls
  srv/pillar/ceph/init.sls
  srv/salt/_modules/cephprocesses.py
  tests/unit/_modules/test_cephprocesses.py
  tests/unit/_modules/test_osd.py
  tox.ini
Labels: enhancement, feature

#1435 cli: prettyprint: force stdout flush in all stdout writes
  cli/common.py
Labels: CLI, bug, needs-backport
