Repository SUSE/DeepSea, pull requests merged in 2018-11, with the labels that each got.

#1442 lrbd service restart instead of reload on `ui_iscsi.deploy`
  srv/modules/runners/ui_iscsi.py
Labels: bug, needs-forwardport

#1449 grafana: use the same time period in every dashboard
  srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
  srv/salt/ceph/monitoring/grafana/files/ceph-osd.json
  srv/salt/ceph/monitoring/grafana/files/node.json
Labels: bug

#1375 Prevent rgw-ssl name collision
  srv/modules/runners/validate.py
  tests/unit/runners/test_validate.py
Labels: needs-backport

#1460 Check configs for deprecated k:v pairs and report
  Makefile
  deepsea.spec.in
  srv/modules/runners/validate.py
  srv/salt/ceph/configuration/files/deprecated_map.yml
  tests/unit/runners/test_validate.py
Labels: enhancement

#1469 Return version instead of printing it
  srv/salt/_modules/cephdisks.py
  tests/unit/_modules/test_cephdisks.py
Labels: cleanup

#1470 monitoring: fix pool usage gauge
  srv/salt/ceph/monitoring/grafana/files/ceph-pools.json
Labels: bug

#1479 [SES5]Add missing bsc bug to v0.8.4 release notes
  CHANGELOG
Labels: documentation
