Repository SUSE/DeepSea, pull requests merged in 2019-06, with the labels that each got.

#1683 monitoring: polulate alertmanager peers must run on salt master
  srv/salt/ceph/stage/deploy/monitoring.sls
Labels: bug

#1682 apparmor: include apparmor in stage 0, teardown by default
  srv/salt/ceph/apparmor/default-teardown.sls
  srv/salt/ceph/stage/prep/minion/common.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default.sls
Labels: enhancement

#1680 restarts: if no fs is present, restart mds without coordination
  srv/salt/ceph/restart/mds/default.sls
Labels: bug, needs-backport

#1685 cephprocesses: do not exit on missing pillar struct
  srv/salt/_modules/cephprocesses.py
  tests/unit/_modules/test_cephprocesses.py
Labels: bug
