Repository SUSE/DeepSea, pull requests merged in 2019-10, with the labels that each got.

#1754 iscsi: SSL enabled deployment by default
  srv/modules/runners/changed.py
  srv/modules/runners/select.py
  srv/salt/_modules/iscsi.py
  srv/salt/ceph/igw/config/apply_iscsi_config.sls
  srv/salt/ceph/igw/config/create_iscsi_config.sls
  srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
  srv/salt/ceph/stage/deploy/core/default.sls
  srv/salt/ceph/stage/iscsi/core/default.sls
  srv/salt/ceph/stage/iscsi/dashboard.sls
  srv/salt/ceph/stage/iscsi/default.sls
  tests/unit/runners/test_changed.py
Labels: bug, feature, needs-backport

#1765 [SES6] ganesha: don't run the upgrade on fresh nodes
  srv/modules/runners/ganesha_upgrade.py
  srv/salt/_modules/ganesha.py
Labels: bug

#1730 Add status function to advise on upgrade order
  deepsea.spec.in
  srv/modules/runners/status.py
  srv/modules/runners/upgrade.py
  srv/modules/utils/status.py
Labels: feature, needs-backport

#1742 Add remove option to the ping to remove multiple ip interface
  srv/modules/runners/net.py
Labels: needs-backport

#1766 [SES6] stage 0: don't show failure in CLI when checking for missing packages
  srv/modules/runners/validate.py
  srv/salt/_modules/deepsea.py
Labels: bug

#1768 ganesha: update ceph.conf in stage 3 instead of 4
  srv/salt/ceph/configuration/files/ceph.conf.j2
  srv/salt/ceph/ganesha/keyring/default.sls
Labels: bug, needs-backport

#1771 [backport][SES6] iscsi: SSL enabled deployment by default
  srv/modules/runners/changed.py
  srv/modules/runners/select.py
  srv/salt/_modules/iscsi.py
  srv/salt/ceph/igw/config/apply_iscsi_config.sls
  srv/salt/ceph/igw/config/create_iscsi_config.sls
  srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
  srv/salt/ceph/stage/deploy/core/default.sls
  srv/salt/ceph/stage/iscsi/core/default.sls
  srv/salt/ceph/stage/iscsi/dashboard.sls
  srv/salt/ceph/stage/iscsi/default.sls
  tests/unit/runners/test_changed.py
Labels: bug, feature

#1731 lrbd to ceph-iscsi upgrade fixes
  srv/salt/_modules/iscsi.py
Labels: needs-backport

#1776 [SES6] lrbd to ceph-iscsi upgrade fixes
  srv/salt/_modules/iscsi.py
Labels: bug

#1773 [SES6] ganesha: update ceph.conf in stage 3 instead of 4
  srv/salt/ceph/configuration/files/ceph.conf.j2
  srv/salt/ceph/ganesha/keyring/default.sls
Labels: bug

#1770 'make pyc' target should fail if unable to compile
  Makefile
Labels: needs-backport

#1781 [SES5] cli: fix simple outputter when printing stage exception
  cli/monitors/terminal_outputter.py
Labels: CLI, bug

#1762 [next] introduce new return structure and refactor modules
  Makefile
  deepsea.spec.in
  doc/graphs/overview.txt
  srv/modules/runners/bootstrap.py
  srv/modules/runners/ext_lib/decorators.py
  srv/modules/runners/ext_lib/exceptions.py
  srv/modules/runners/ext_lib/operation.py
  srv/modules/runners/ext_lib/utils.py
  srv/modules/runners/ext_lib/validator.py
  srv/modules/runners/mon.py
  srv/modules/runners/test.py
  srv/salt/_modules/ext_lib/__init__.py
  srv/salt/_modules/ext_lib/podman.py
  srv/salt/_modules/ext_lib/utils.py
  srv/salt/_modules/keyring.py
  srv/salt/_modules/mon.py
  srv/salt/_modules/podman.py
Labels: next

#1785 [next] Refine the runner function decorator
  srv/modules/runners/ext_lib/decorators.py
  srv/modules/runners/ext_lib/exceptions.py
  srv/modules/runners/ext_lib/utils.py
  srv/modules/runners/test.py
Labels: next

#1787 [next] add help() func to test runner
  srv/modules/runners/ext_lib/doc.py
  srv/modules/runners/test.py
Labels: next

#1788 [next] Extend the demo runner (test.py) with interactive prompts
  srv/modules/runners/config.py
  srv/modules/runners/ext_lib/decorators.py
  srv/modules/runners/ext_lib/exceptions.py
  srv/modules/runners/ext_lib/hash_dir.py
  srv/modules/runners/ext_lib/operation.py
  srv/modules/runners/ext_lib/utils.py
  srv/modules/runners/test.py
Labels: next
