Repository SUSE/DeepSea, pull requests merged in 2019-04, with the labels that each got.

#1601 ganesha: find pool during stage execution (instead of in parsing phase)
  srv/salt/ceph/ganesha/rados_config.sls
  srv/salt/ceph/stage/ganesha/core/default.sls
Labels: bug

#1596 iscsi: use iSCSi gateway public IP address in dashboard configuration
  srv/salt/ceph/stage/iscsi/core/default.sls
Labels: bug

#1602 cli: fix print of target name in stage dry-run
  cli/deepsea.py
Labels: CLI, bug

#1617 Makefile: make "make rpm" less likely to produce a wrong version number
  Makefile
Labels: bug

#1613 monitoring: update smartmon.sh, fix label dimension inconsistency
  srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh
Labels: monitoring

#1612 crc_method: deepsea_minions can be a compound target
  srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default-update-reboot.sls
  srv/salt/ceph/stage/prep/minion/default.sls
Labels: bug

#1618 monitoring: set grafana default theme to light
  srv/salt/ceph/monitoring/grafana/default.sls
Labels: monitoring

#1556 [SES5] monitoring: update smartmon.sh, fix label dimension inconsistency
  srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh
Labels: bug, needs-forwardport

#1620 [SES5] ui_iscsi: restart iSCSI gateways sequentially
  srv/modules/runners/ui_iscsi.py
Labels: bug

#1621 rpm: declare runtime dependencies in the spec file
  deepsea.spec.in
Labels: bug

#1626 disks runner: guard destroyed() against roles:master being absent
  srv/modules/runners/disks.py
Labels: bug

#1627 monitoring: add most pieces for scale out monitoring (SES-261, SES-79)
  Makefile
  deepsea.spec.in
  srv/salt/ceph/monitoring/alertmanager/default.sls
  srv/salt/ceph/monitoring/alertmanager/files/alertmanager.sysconfig.j2
  srv/salt/ceph/monitoring/alertmanager/init.sls
  srv/salt/ceph/monitoring/alertmanager/populate_peers.sls
  srv/salt/ceph/monitoring/grafana/create_configs.sls
  srv/salt/ceph/monitoring/grafana/default.sls
  srv/salt/ceph/monitoring/grafana/populate_datasources.sls
  srv/salt/ceph/monitoring/init.sls
  srv/salt/ceph/monitoring/prometheus/alertmanager.sls
  srv/salt/ceph/monitoring/prometheus/default.sls
  srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
  srv/salt/ceph/monitoring/prometheus/init.sls
  srv/salt/ceph/monitoring/prometheus/populate_mgr_scrape_configs.sls
  srv/salt/ceph/monitoring/prometheus/populate_scrape_configs.sls
  srv/salt/ceph/monitoring/prometheus/push_mgr_scrape_configs.sls
  srv/salt/ceph/monitoring/prometheus/push_scrape_configs.sls
  srv/salt/ceph/rescind/alertmanager/default-nop.sls
  srv/salt/ceph/rescind/alertmanager/default.sls
  srv/salt/ceph/rescind/alertmanager/init.sls
  srv/salt/ceph/stage/deploy/monitoring.sls
Labels: enhancement, monitoring

#1609 dashboard: support for enabling/disabling SSL and set certificates
  srv/salt/ceph/dashboard/default.sls
Labels: enhancement

#1608 iscsi: REST API ssl support
  srv/salt/ceph/igw/config/apply_iscsi_config.sls
  srv/salt/ceph/igw/config/create_iscsi_config.sls
  srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
  srv/salt/ceph/stage/iscsi/core/default.sls
Labels: enhancement

#1630 ceph-volume: use re to extract json string from c-v output
  srv/salt/_modules/dg.py
Labels: bug, question

#1631 do no parse ceph output when no valid json
  srv/modules/runners/disks.py
Labels: bug

#1628 core: do not skip disks that are not used by ceph
  srv/salt/_modules/cephdisks.py
Labels: bug
