Repository SUSE/DeepSea, pull requests merged in 2019-07, with the labels that each got.

#1691 apparmor: ignore aa-disabled return code
  srv/salt/ceph/apparmor/default-disable.sls
Labels: bug

#1686 rescind/ntp: remove the correct RPM
  srv/salt/ceph/rescind/time/ntp/default.sls
Labels: bug

#1699 tests: adapt to new pytest syntax (pytest.raises)
  tests/unit/_modules/test_dg.py
Labels: priority

#1687 restarts: if no fs is present, restart mds without coordination
  srv/salt/ceph/restart/mds/default.sls
Labels: bug

#1694 mds: numerical mds names are forbidden (have been deprecated since 2014)
  srv/salt/_modules/cephprocesses.py
  srv/salt/_modules/mds.py
  srv/salt/ceph/mds/auth/default.sls
  srv/salt/ceph/mds/default.sls
  srv/salt/ceph/mds/key/default.sls
  srv/salt/ceph/mds/keyring/default.sls
  srv/salt/ceph/mds/restart/controlled/default-shared.sls
  srv/salt/ceph/mds/restart/controlled/default.sls
  srv/salt/ceph/mds/restart/force/default.sls
  srv/salt/ceph/mds/shutdown.sls
  srv/salt/ceph/rescind/mds/default.sls
  srv/salt/ceph/rescind/mds/keyring/default.sls
  tests/unit/_modules/test_cephprocesses.py
  tests/unit/_modules/test_mds.py
Labels: bug

#1693 SES5: fix mds numerical names
  srv/salt/_modules/mds.py
  srv/salt/ceph/mds/auth/default.sls
  srv/salt/ceph/mds/default.sls
  srv/salt/ceph/mds/key/default.sls
  srv/salt/ceph/mds/keyring/default.sls
  srv/salt/ceph/mds/migrate-numerical-names.sls
  srv/salt/ceph/mds/remove-mds-with-numeric-names.sls
  srv/salt/ceph/mds/restart/controlled/default-shared.sls
  srv/salt/ceph/mds/restart/controlled/default.sls
  srv/salt/ceph/mds/restart/force/default.sls
  srv/salt/ceph/mds/shutdown.sls
  srv/salt/ceph/rescind/mds/default.sls
  srv/salt/ceph/rescind/mds/keyring/default.sls
  tests/unit/_modules/test_mds.py
Labels: backported, bug

#1708 dg: workaround ceph-volume infused bugs
  srv/salt/_modules/dg.py
  tests/unit/_modules/test_dg.py
Labels: bug

#1709 monitoring: alertmanager sysconfig needs --cluster.listen-address (bs…
  srv/salt/ceph/monitoring/alertmanager/default.sls
  srv/salt/ceph/monitoring/alertmanager/files/alertmanager.sysconfig.j2
  srv/salt/ceph/monitoring/alertmanager/populate_peers.sls
Labels: bug, monitoring

#1713 drivegroups: allow lower case sizing units
  srv/salt/_modules/dg.py
  srv/salt/ceph/configuration/files/drive_groups.yml
  tests/unit/_modules/test_dg.py
Labels: enhancement

#1690 disks: improve `disks.list` and various other things
  srv/modules/runners/disks.py
  srv/salt/_modules/cephdisks.py
  srv/salt/_modules/dg.py
  srv/salt/_modules/osd.py
  tests/unit/_modules/test_cephdisks.py
  tests/unit/_modules/test_dg.py
  tests/unit/_modules/test_osd.py
  tests/unit/helper/factories.py
  tests/unit/runners/test_disks.py
Labels: enhancement

#1712 The disk_led runner crashes (bsc#1142821)
  srv/modules/runners/disk_led.py
  tests/unit/runners/test_disk_led.py
Labels: bug

#1714 Allow literal wal db journal sizes
  srv/salt/_modules/dg.py
  tests/unit/_modules/test_dg.py
Labels: bug, enhancement

#1715 remove/replace: add path to status report for better identification
  srv/modules/runners/osd.py
  srv/salt/_modules/cephdisks.py
Labels: enhancement
