Repository SUSE/DeepSea, pull requests merged in 2019-03, with the labels that each got.

#1559 monitoring: defer deployment to stage 3
  srv/salt/ceph/stage/configure/default.sls
  srv/salt/ceph/stage/deploy/default.sls
  srv/salt/ceph/stage/deploy/monitoring.sls
Labels: bug

#1516 Kill iperf3 processes when complete
  Makefile
  srv/modules/runners/net.py
  srv/salt/_modules/multi.py
  srv/salt/ceph/functests/1node/init.sls
  srv/salt/ceph/functests/1node/multi/init.sls
  srv/salt/ceph/tests/iperf3/init.sls
  tests/unit/_modules/test_multi.py
Labels: needs-forwardport

#1565 Add central /etc/deepsea config directory.
  Makefile
  deepsea.spec.in
  srv/salt/ceph/configuration/files/drive_groups.yml
Labels: enhancement

#1562 scrape target partitioning, grafana config for dashboard (SES-261)
  srv/modules/runners/populate.py
  srv/salt/_modules/scrape_targets.py
  srv/salt/ceph/monitoring/grafana/default.sls
  srv/salt/ceph/monitoring/prometheus/push_scrape_configs.sls
  tests/unit/_modules/test_scrape_targets.py
Labels: feature, monitoring

#1566 [SES5] qa: drop health-ok.sh and associated scripting
  Makefile
  deepsea.spec.in
  qa/README
  qa/README.wip
  qa/common/common.sh
  qa/common/deploy.sh
  qa/common/helper.sh
  qa/common/json.sh
  qa/common/nfs-ganesha.sh
  qa/common/policy.sh
  qa/common/pool.sh
  qa/common/rbd.sh
  qa/common/rgw.sh
  qa/common/zypper.sh
  qa/osd-config/ovh/README.md
  qa/osd-config/ovh/bs_dedicated_db.yaml
  qa/osd-config/ovh/bs_dedicated_db_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_db_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal.yaml
  qa/osd-config/ovh/bs_dedicated_wal_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_crypt.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed.yaml
  qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed_crypt.yaml
  qa/osd-config/ovh/fs_dedicated_journal.yaml
  qa/osd-config/ovh/fs_dedicated_journal_crypt.yaml
  qa/suites/basic/health-ok.sh
  qa/suites/basic/health-openattic.sh
  qa/suites/basic/stage-5.sh
  qa/suites/ceph-test/fs_to_bs_migration.sh
  qa/suites/ceph-test/librbd.sh
  qa/suites/ceph-test/pynfs.sh
Labels: QA

#1570 prometheus: fix populate_mgr_scrape_configs states to work with deepsea-cli
  srv/salt/ceph/monitoring/prometheus/populate_mgr_scrape_configs.sls
Labels: CLI, bug

#1474 Add runner to enable/disable storage enclosure LED
  Makefile
  deepsea.spec.in
  srv/modules/runners/disk_led.py
  srv/pillar/ceph/disk_led.sls
  srv/pillar/ceph/init.sls
  srv/salt/ceph/packages/common/default.sls
  tests/unit/runners/test_disk_led.py
Labels: feature, needs-qa

#1575 cli: fix stdout/stderr redirection for python 2
  cli/stage_parser.py
Labels: bug, needs-backport

#1576 cli: automatically wrap of step lines
  cli/common.py
  cli/monitors/terminal_outputter.py
Labels: CLI, bug

#1582 [backport] [SES5] cli: fix stdout/stderr redirection for python 2
  cli/stage_parser.py
Labels: bug

#1584 cli: fix function args string formating
  cli/monitor.py
Labels: CLI, bug

#1571 cli: fix simple outputter when printing stage exception
  cli/monitors/terminal_outputter.py
Labels: CLI, bug

#1569 cli: handles render failure when minion does not respond
  cli/stage_parser.py
Labels: CLI, bug

#1573 iscsi: fix deployment of iSCSI gateways
  Makefile
  deepsea.spec.in
  srv/modules/modules/master.py
  srv/modules/runners/select.py
  srv/salt/_modules/deepsea.py
  srv/salt/ceph/functests/1node/init.sls
  srv/salt/ceph/igw/config/apply_iscsi_config.sls
  srv/salt/ceph/igw/config/create_iscsi_config.sls
  srv/salt/ceph/igw/config/default.sls
  srv/salt/ceph/igw/config/init.sls
  srv/salt/ceph/igw/default.sls
  srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
  srv/salt/ceph/igw/restart/controlled/default.sls
  srv/salt/ceph/igw/restart/controlled/init.sls
  srv/salt/ceph/igw/restart/default.sls
  srv/salt/ceph/igw/restart/reload/default.sls
  srv/salt/ceph/igw/restart/reload/init.sls
  srv/salt/ceph/packages/common/default.sls
  srv/salt/ceph/stage/deploy/core/default.sls
  srv/salt/ceph/stage/iscsi/core/default.sls
Labels: bug

#1529 [SES5] Do not return content in case there is no matching by_path
  srv/salt/_modules/osd.py
  tests/unit/_modules/test_osd.py
Labels: bug
