Repository SUSE/DeepSea, pull requests merged in 2019-02, with the labels that each got.

#1492 Move pytest to base_python 3.6 and adapt tests accordingly
  Makefile
  srv/modules/runners/push.py
  tests/unit/_modules/test_cephdisks.py
  tests/unit/_modules/test_osd.py
  tests/unit/_modules/test_rgw.py
  tests/unit/runners/test_changed.py
  tests/unit/runners/test_proposal.py
  tests/unit/runners/test_push.py
  tests/unit/runners/test_sharedsecret.py
  tox.ini
Labels: cleanup, help wanted

#1518 Check for digit before 'p'
  srv/salt/_modules/osd.py
  tests/unit/_modules/test_osd.py
Labels: needs-forwardport

#1468 [SES5] Add rebuild orchestration, obliterate state
  Makefile
  deepsea.spec.in
  srv/modules/runners/advise.py
  srv/modules/runners/filequeue.py
  srv/salt/ceph/functests/1node/rebuild/init.sls
  srv/salt/ceph/obliterate/default.sls
  srv/salt/ceph/obliterate/init.sls
  srv/salt/ceph/obliterate/lock/default.sls
  srv/salt/ceph/obliterate/lock/init.sls
  srv/salt/ceph/obliterate/unlock/default.sls
  srv/salt/ceph/obliterate/unlock/init.sls
  srv/salt/ceph/rebuild/default.sls
  srv/salt/ceph/rebuild/init.sls
  tests/unit/runners/test_filequeue.py
Labels: needs-forwardport

#1524 Makefile: pass --long option to git describe
  Makefile
Labels: needs-backport

#1538 Change validation tag from 'openattic' to 'openattic-disabled'
  srv/modules/runners/validate.py
Labels: documentation, enhancement

#1531 Handle broken symlinks
  srv/salt/_modules/osd.py
  srv/salt/ceph/functests/1node/symlink/init.sls
  srv/salt/ceph/tests/symlink/init.sls
  tests/unit/_modules/test_osd.py
Labels: needs-forwardport

#1542 Address removal of dmcrypt partitions
  srv/salt/_modules/osd.py
  tests/unit/_modules/test_osd.py
Labels: needs-forwardport

#1486 Assign drives based on filter rules (DriveGroups) SES-150
  .gitignore
  Makefile
  cli/tests/test_monitor.py
  deepsea.spec.in
  srv/modules/runners/disks.py
  srv/modules/runners/push.py
  srv/pillar/ceph/init.sls
  srv/salt/_modules/dg.py
  srv/salt/ceph/configuration/files/drive_groups.yml
  srv/salt/ceph/stage/deploy/core/default.sls
  tests/unit/_modules/test_dg.py
  tests/unit/runners/test_disks.py
Labels: DNM

#1541 Add Prometheus and Grafana roles (SES-199)
  Makefile
  deepsea.spec.in
  doc/examples/policy.cfg-rolebased
  srv/modules/runners/populate.py
  srv/salt/_modules/cephprocesses.py
  srv/salt/ceph/monitoring/grafana/default.sls
  srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
  srv/salt/ceph/monitoring/grafana/files/ceph-osd.json
  srv/salt/ceph/monitoring/grafana/files/ceph-pools.json
  srv/salt/ceph/monitoring/grafana/files/ceph-rbd.json
  srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json
  srv/salt/ceph/monitoring/grafana/files/ceph-rgw.json
  srv/salt/ceph/monitoring/grafana/files/node.json
  srv/salt/ceph/monitoring/grafana/files/ses_dashboards.yaml.j2
  srv/salt/ceph/monitoring/grafana/files/ses_datasource.yaml.j2
  srv/salt/ceph/monitoring/grafana/init.sls
  srv/salt/ceph/monitoring/grafana/populate_datasources.sls
  srv/salt/ceph/monitoring/grafana/restart.sls
  srv/salt/ceph/monitoring/prometheus/exporters/ceph_exporter.sls
  srv/salt/ceph/monitoring/prometheus/exporters/mgr_exporter.sls
  srv/salt/ceph/monitoring/prometheus/files/minion.yml.j2
  srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
  srv/salt/ceph/monitoring/prometheus/install.sls
  srv/salt/ceph/monitoring/prometheus/populate_mgr_scrape_configs.sls
  srv/salt/ceph/monitoring/prometheus/populate_scrape_configs.sls
  srv/salt/ceph/monitoring/prometheus/push_mgr_scrape_configs.sls
  srv/salt/ceph/monitoring/prometheus/push_scrape_configs.sls
  srv/salt/ceph/monitoring/prometheus/restart.sls
  srv/salt/ceph/monitoring/prometheus/update_service_discovery.sls
  srv/salt/ceph/rescind/grafana/default-nop.sls
  srv/salt/ceph/rescind/grafana/default.sls
  srv/salt/ceph/rescind/grafana/init.sls
  srv/salt/ceph/rescind/prometheus/default-nop.sls
  srv/salt/ceph/rescind/prometheus/default.sls
  srv/salt/ceph/rescind/prometheus/init.sls
  srv/salt/ceph/restart/default.sls
  srv/salt/ceph/restart/grafana/default.sls
  srv/salt/ceph/restart/grafana/init.sls
  srv/salt/ceph/restart/prometheus/default.sls
  srv/salt/ceph/restart/prometheus/init.sls
  srv/salt/ceph/stage/configure/default.sls
  srv/salt/ceph/stage/deploy/core/default.sls
  srv/salt/ceph/stage/deploy/default.sls
Labels: monitoring

#1548 monitoring: restarts, avoid "matched no target"
  srv/salt/ceph/restart/grafana/default.sls
  srv/salt/ceph/restart/prometheus/default.sls
Labels: bug

#1545 populate should overwrite the stack/default tree at all times
  srv/modules/runners/populate.py
Labels: bug
