Repository SUSE/DeepSea, pull requests merged in 2019-11, with the labels that each got.

#1793 srv/salt/ceph/purge: Changed order of runner calls
  srv/salt/ceph/purge/default.sls
Labels: bug

#1782 [SES6] Simplify management of tuned
  Makefile
  deepsea.spec.in
  srv/salt/ceph/functests/1node/tuned/init.sls
  srv/salt/ceph/functests/1node/tuned/off/init.sls
  srv/salt/ceph/stage/deploy/core/default.sls
  srv/salt/ceph/tuned/files/ceph-mon/tuned.conf
  srv/salt/ceph/tuned/files/latency.conf
  srv/salt/ceph/tuned/files/throughput.conf
  srv/salt/ceph/tuned/latency/default.sls
  srv/salt/ceph/tuned/latency/disabled.sls
  srv/salt/ceph/tuned/latency/init.sls
  srv/salt/ceph/tuned/mgr/default-off.sls
  srv/salt/ceph/tuned/mgr/default.sls
  srv/salt/ceph/tuned/mgr/init.sls
  srv/salt/ceph/tuned/mon/default-off.sls
  srv/salt/ceph/tuned/mon/default.sls
  srv/salt/ceph/tuned/mon/init.sls
  srv/salt/ceph/tuned/off/default.sls
  srv/salt/ceph/tuned/off/init.sls
  srv/salt/ceph/tuned/osd/default-off.sls
  srv/salt/ceph/tuned/osd/default.sls
  srv/salt/ceph/tuned/osd/init.sls
  srv/salt/ceph/tuned/throughput/default.sls
  srv/salt/ceph/tuned/throughput/disabled.sls
  srv/salt/ceph/tuned/throughput/init.sls
Labels: needs-forwardport

#1795 [SES6] Split output to console and Salt log
  Makefile
  etc/salt/master.d/logging.conf
  srv/modules/runners/disks.py
  srv/modules/runners/osd.py
  srv/modules/utils/tee.py
  tox.ini
Labels: needs-forwardport

#1800 [SES6] Allow for graceful rerunning when removing the cephfs configuration
  srv/salt/ceph/remove/mds/default.sls
Labels: needs-forwardport

#1804 ADD doc/examples/policy.cfg-full: full example using all roles
  doc/examples/policy.cfg-full
Labels: needs-backport
