Repository SUSE/DeepSea, pull requests merged in 2019-05, with the labels that each got.

#1643 dg: use re.search instead of re.match
  srv/salt/_modules/dg.py
  tests/unit/_modules/test_dg.py
Labels: bug

#1648 tox: use python3 instead of python3.6
  Makefile
  tox.ini
Labels: QA, bug

#1641 runners/deepsea.py: fix deepsea RPM version detection
  srv/modules/runners/deepsea.py
  tests/unit/runners/test_deepsea.py
Labels: needs-backport

#1645 Remove obsolete includes
  srv/salt/ceph/monitoring/default.sls
Labels: cleanup

#1644 By default teardown apparmor
  srv/salt/ceph/apparmor/default-teardown.sls
  srv/salt/ceph/apparmor/default.sls
Labels: bug

#1615 chrony: allow NTP access from local network
  srv/salt/ceph/time/chrony/files/chrony.conf.j2
Labels: bug

#1654 modules: expr_form has been deprecated over tgt_type
  srv/modules/runners/benchmark.py
  srv/modules/runners/cmd.py
  srv/modules/runners/disks.py
  tests/unit/runners/test_disks.py
Labels: bug

#1640 NFS-Ganesha and iSCSI upgrade
  Makefile
  cli/monitors/terminal_outputter.py
  deepsea.spec.in
  srv/modules/runners/ganesha_upgrade.py
  srv/modules/runners/iscsi_upgrade.py
  srv/modules/runners/select.py
  srv/salt/_modules/cephprocesses.py
  srv/salt/_modules/ganesha.py
  srv/salt/_modules/iscsi.py
  srv/salt/_modules/keyring.py
  srv/salt/_states/deepsea.py
  srv/salt/ceph/configuration/files/rgw-ssl.conf
  srv/salt/ceph/configuration/files/rgw.conf
  srv/salt/ceph/dashboard/default.sls
  srv/salt/ceph/ganesha/auth/default.sls
  srv/salt/ceph/ganesha/key/default.sls
  srv/salt/ceph/ganesha/keyring/default.sls
  srv/salt/ceph/ganesha/restart/controlled/default.sls
  srv/salt/ceph/igw/default.sls
  srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
  srv/salt/ceph/igw/restart/controlled/default.sls
  srv/salt/ceph/igw/restart/force/default.sls
  srv/salt/ceph/restart/igw/lax/default.sls
  srv/salt/ceph/rgw/dashboard.sls
  srv/salt/ceph/rgw/default.sls
  srv/salt/ceph/stage/ganesha/default.sls
  srv/salt/ceph/stage/ganesha/migrate.sls
  srv/salt/ceph/stage/iscsi/core/default.sls
  srv/salt/ceph/stage/iscsi/default.sls
  srv/salt/ceph/stage/iscsi/migrate.sls
  tests/unit/_modules/test_cephprocesses.py
Labels: feature

#1656 mds: move reset/shrink-mds-cluster (SES-364)
  srv/salt/ceph/functests/1node/restart/mds.sls
  srv/salt/ceph/mds/reset-mds-cluster.sls
  srv/salt/ceph/mds/shrink-mds-cluster.sls
  srv/salt/ceph/restart/mds/default-shrink.sls
Labels: cleanup, enhancement

#1652 Use correct config name for Dashboard SSL port
  srv/salt/ceph/dashboard/default.sls
Labels: bug

#1657 SSL certificate deployment and management
  Makefile
  deepsea.spec.in
  srv/modules/runners/select.py
  srv/salt/_modules/deepsea.py
  srv/salt/ceph/dashboard/default.sls
  srv/salt/ceph/igw/config/create_iscsi_config.sls
  srv/salt/ceph/monitoring/grafana/create_configs.sls
  srv/salt/ceph/ssl/default.sls
  srv/salt/ceph/ssl/distribute_ca.sls
  srv/salt/ceph/ssl/init.sls
  srv/salt/ceph/stage/configure/default.sls
  srv/salt/ceph/stage/deploy/core/default.sls
Labels: feature

#1664 srv/pillar/ceph/README should be installed
  Makefile
  deepsea.spec.in
Labels: enhancement

#1661 dg: make error conditions consistent; don't execute a error message
  srv/salt/_modules/dg.py
  tests/unit/_modules/test_dg.py
Labels: bug

#1670 iscsi: fix gateway URL when using IPv6 address
  srv/salt/_modules/iscsi.py
Labels: bug

#1663 Deploy Prometheus Alertmanager SNMP receiver
  doc/pillar/alertmanager_receiver_snmp.yml
  srv/salt/ceph/monitoring/alertmanager/default.sls
  srv/salt/ceph/rescind/alertmanager/default.sls
Labels: feature

#1671 iscsi: use FQDN in gateways hostnames
  srv/salt/_modules/iscsi.py
  srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
  srv/salt/ceph/packages/common/default.sls
Labels: enhancement

#1666 monitoring: manage salt's fileserver cache in monitoring deployment
  srv/salt/ceph/stage/deploy/monitoring.sls
Labels: bug

#1674 osd: do not assign value to property
  srv/salt/_modules/osd.py
Labels: bug

#1669 monitoring: iterate over pillar yaml to generate prometheus yaml
  srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
Labels: bug

#1675 apparmor: fix mgr profile after nautilus changes
  srv/salt/ceph/apparmor/files/ceph.d/common
  srv/salt/ceph/apparmor/files/usr.bin.ceph-mgr
  srv/salt/ceph/apparmor/files/usr.sbin.oaconfig
Labels: bug
