Repository SUSE/DeepSea, pull requests merged in 2019-09, with the labels that each got.

#1734 [next] Add 'ext_lib' runners to RPM spec
  deepsea.spec.in
Labels: next

#1735 [next] refactor bootstrap, mon and mgr code
  Makefile
  deepsea.spec.in
  srv/modules/runners/bootstrap.py
  srv/modules/runners/ceph.py
  srv/modules/runners/config.py
  srv/modules/runners/ext_lib/hash_dir.py
  srv/modules/runners/ext_lib/utils.py
  srv/modules/runners/mgr.py
  srv/modules/runners/mon.py
  srv/pillar/ceph/init.sls
  srv/pillar/ceph/internal.yml
  srv/salt/_modules/podman.py
  srv/salt/ceph/configuration/files/ceph.conf.j2
  srv/salt/ceph/permissions/default.sls
  srv/salt/ceph/permissions/init.sls
Labels: next

#1744 [next] draft for new readme
  README.md
Labels: next

#1750 cephfs: fix pool creation prerequisite (bsc#1149557)
  srv/salt/ceph/mds/pools/default.sls
Labels: bug, needs-backport

#1751 cephfs: fix pool creation prerequisite
  srv/salt/ceph/mds/pools/default.sls
Labels: backported, bug

#1755 stage 5: actually call remove.mds in stage 5
  srv/salt/ceph/stage/removal/default.sls
Labels: bug

#1743 ganesha: report runner to give support info about nfs-ganesha
  srv/modules/runners/ganesha.py
  srv/salt/_modules/ganesha.py
Labels: feature, needs-backport

#1738 [SES6] Handle the apparmor disabled at boot scenario
  srv/salt/ceph/apparmor/default-teardown.sls
Labels: needs-forwardport

#1741 ganesha: don't run the upgrade on fresh nodes
  srv/modules/runners/ganesha_upgrade.py
  srv/salt/_modules/ganesha.py
Labels: bug, needs-backport

#1756 iscsi: fix iscsi restart before upgrade to ceph-iscsi
  srv/salt/_states/deepsea.py
  srv/salt/ceph/igw/restart/controlled/default.sls
Labels: bug, needs-backport

#1753 cephfs: use ceph fs fail command to bring down MDS daemons before remove (bsc#1149530)
  Makefile
  deepsea.spec.in
  srv/salt/ceph/remove/cephfs/default.sls
  srv/salt/ceph/remove/cephfs/init.sls
  srv/salt/ceph/stage/removal/default.sls
Labels: bug, needs-backport

#1758 [SES6] ganesha: report runner to give support info about nfs-ganesha
  srv/modules/runners/ganesha.py
  srv/salt/_modules/ganesha.py
Labels: feature

#1760 [SES6] iscsi: fix iscsi restart before upgrade to ceph-iscsi
  srv/salt/_states/deepsea.py
  srv/salt/ceph/igw/restart/controlled/default.sls
Labels: bug

#1761 stage 0: don't show failure in CLI when checking for missing packages
  srv/modules/runners/validate.py
  srv/salt/_modules/deepsea.py
Labels: bug
