Repository SUSE/DeepSea, pull requests merged in 2021-02, with the labels that each got.

#1868 monitoring: enable custom scrape configurations
  srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
Labels: feature

#1865 osd: add method to zap simple osds
  srv/modules/runners/osd.py
Labels: bug, needs-qa

#1872 Rework config change detection to handle global.conf correctly (bsc#1181183)
  man/deepsea-commands.7
  srv/modules/runners/changed.py
  srv/salt/ceph/functests/1node/restart/common.sls
  srv/salt/ceph/stage/deploy/core/default.sls
  srv/salt/ceph/stage/iscsi/core/default.sls
  tests/unit/runners/test_changed.py
Labels: bug
